# Generated by Django 3.0.5 on 2020-12-16 15:58

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accession',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('accessionName', models.TextField(null=True)),
                ('accessionNumber', models.TextField(null=True)),
                ('acquisitionDate', models.IntegerField(null=True)),
                ('aegis', models.IntegerField(null=True)),
                ('available', models.IntegerField(null=True)),
                ('coll_collDate', models.IntegerField(null=True)),
                ('countryOfOrigin_code3', models.TextField(null=True)),
                ('countryOfOrigin_name', models.TextField(null=True)),
                ('countryOfOrigin_region_name', models.TextField(null=True)),
                ('sampStat', models.IntegerField(null=True)),
                ('crop_name', models.TextField(null=True)),
                ('doi', models.TextField(null=True)),
                ('historic', models.IntegerField(null=True)),
                ('id', models.IntegerField(null=True)),
                ('institute_fullName', models.TextField(null=True)),
                ('institute_acronym', models.TextField(null=True)),
                ('geo_longitude', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('geo_latitude', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('geo_elevation', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BiologicalStatus',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('id_mcpd', models.IntegerField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('indicators', djongo.models.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorKind',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorValue',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('name', models.TextField()),
                ('indicator', models.ForeignKey(db_column='indicator', on_delete=django.db.models.deletion.DO_NOTHING, to='indicators.Indicator')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('id_genesys', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('median', models.DecimalField(decimal_places=5, max_digits=5)),
                ('mean', models.DecimalField(decimal_places=5, max_digits=5)),
                ('quartils', models.DecimalField(decimal_places=5, max_digits=5)),
                ('percentil_5', models.DecimalField(decimal_places=5, max_digits=5)),
                ('percentil_95', models.DecimalField(decimal_places=5, max_digits=5)),
                ('desv_stand', models.DecimalField(decimal_places=5, max_digits=5)),
                ('indicator_value', models.ForeignKey(db_column='indicator_value', on_delete=django.db.models.deletion.DO_NOTHING, to='indicators.IndicatorValue')),
            ],
        ),
        migrations.AddField(
            model_name='indicator',
            name='indicator_kind',
            field=models.ForeignKey(db_column='indicator_kind', on_delete=django.db.models.deletion.DO_NOTHING, to='indicators.IndicatorKind'),
        ),
    ]
