# Generated by Django 3.0.5 on 2021-06-25 20:59

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import indicators.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'indicators_crop',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('pref', models.TextField()),
                ('crop', djongo.models.fields.ArrayField(model_container=indicators.models.Crop, model_form_class=indicators.models.CropForm)),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorPeriod',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('period', models.TextField()),
                ('indicator', models.ForeignKey(db_column='indicator', on_delete=django.db.models.deletion.DO_NOTHING, to='indicators.Indicator')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorType',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorValue',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('cellid', models.IntegerField(db_index=True, null=True)),
                ('month1', models.FloatField(db_index=True)),
                ('month2', models.FloatField(db_index=True)),
                ('month3', models.FloatField(db_index=True)),
                ('month4', models.FloatField(db_index=True)),
                ('month5', models.FloatField(db_index=True)),
                ('month6', models.FloatField(db_index=True)),
                ('month7', models.FloatField(db_index=True)),
                ('month8', models.FloatField(db_index=True)),
                ('month9', models.FloatField(db_index=True)),
                ('month10', models.FloatField(db_index=True)),
                ('month11', models.FloatField(db_index=True)),
                ('month12', models.FloatField(db_index=True)),
                ('indicator_period', models.ForeignKey(db_column='indicator_period', on_delete=django.db.models.deletion.PROTECT, related_name='indsper', to='indicators.IndicatorPeriod')),
            ],
        ),
        migrations.AddField(
            model_name='indicator',
            name='indicator_type',
            field=djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='indicators.IndicatorType'),
        ),
        migrations.CreateModel(
            name='Accession',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField(db_index=True, null=True)),
                ('number', models.TextField(null=True)),
                ('acq_date', models.TextField(null=True)),
                ('aegis', models.TextField(null=True)),
                ('available', models.TextField(null=True)),
                ('coll_date', models.TextField(null=True)),
                ('country_code', models.TextField(null=True)),
                ('country_name', models.TextField(db_index=True, null=True)),
                ('country_region_name', models.TextField(null=True)),
                ('samp_stat', models.TextField(db_index=True, null=True)),
                ('doi', models.TextField(null=True)),
                ('historic', models.IntegerField(null=True)),
                ('id', models.IntegerField(db_index=True, null=True)),
                ('institute_fullname', models.TextField(null=True)),
                ('institute_acronym', models.TextField(db_index=True, null=True)),
                ('geo_lon', models.FloatField(null=True)),
                ('geo_lat', models.FloatField(null=True)),
                ('geo_ele', models.TextField(null=True)),
                ('cellid', models.IntegerField(db_index=True)),
                ('taxonomy_genus', models.TextField(db_index=True)),
                ('taxonomy_sp_author', models.TextField(db_index=True)),
                ('taxonomy_species', models.TextField(db_index=True)),
                ('taxonomy_taxon_name', models.TextField(db_index=True)),
                ('crop', models.ForeignKey(db_column='crop', on_delete=django.db.models.deletion.DO_NOTHING, to='indicators.Crops')),
            ],
        ),
        migrations.AddIndex(
            model_name='indicatorvalue',
            index=models.Index(fields=['indicator_period', 'month1', 'month2', 'month3', 'month4', 'month5', 'month6', 'month7', 'month8', 'month9', 'month10', 'month11', 'month12'], name='indicators__indicat_785888_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorvalue',
            index=models.Index(fields=['indicator_period', 'month1', 'month2', 'month3'], name='indicators__indicat_06f730_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorvalue',
            index=models.Index(fields=['indicator_period', 'month4', 'month5', 'month6'], name='indicators__indicat_a6af83_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorvalue',
            index=models.Index(fields=['indicator_period', 'month7', 'month8', 'month9'], name='indicators__indicat_2b5a77_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorvalue',
            index=models.Index(fields=['indicator_period', 'month10', 'month11', 'month12'], name='indicators__indicat_6682a6_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorvalue',
            index=models.Index(fields=['indicator_period', 'month9', 'month10', 'month11', 'month12', 'month1', 'month2', 'month3'], name='indicators__indicat_a96e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='accession',
            index=models.Index(fields=['crop', 'name', 'country_name', 'institute_acronym', 'samp_stat'], name='indicators__crop_a2d99d_idx'),
        ),
        migrations.AddIndex(
            model_name='accession',
            index=models.Index(fields=['crop', 'name'], name='indicators__crop_d71c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='accession',
            index=models.Index(fields=['crop', 'country_name'], name='indicators__crop_e487a2_idx'),
        ),
        migrations.AddIndex(
            model_name='accession',
            index=models.Index(fields=['geo_lon', 'geo_lat'], name='indicators__geo_lon_97c395_idx'),
        ),
    ]
